<h1 style="color:red; text-align:center;">Titanic Survive Prediction (Random Forest Model)</h1>

In [49]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [50]:
df=pd.read_csv(r"C:\Users\bmsha\Downloads\titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

<h1 style="color:red;">Data Cleaning</h1>

In [51]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [53]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [54]:
df[['Cabin','Embarked']]=df[['Cabin','Embarked']].fillna(method='bfill')

In [55]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          1
Embarked       0
dtype: int64

In [56]:
df['Sex']=df['Sex'].map({'female':0,'male':1})
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,C85,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,C123,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",1,27.0,0,0,211536,13.0000,B42,S
887,888,1,1,"Graham, Miss. Margaret Edith",0,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,28.0,1,2,W./C. 6607,23.4500,C148,S
889,890,1,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",1,32.0,0,0,370376,7.7500,NaN,Q

In [57]:
from sklearn.model_selection import train_test_split

x=df[['Pclass','Sex','Age','SibSp','Parch','Fare']]
y=df['Survived']

In [58]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

<h1 style="color:red;"> Model building</h1>

In [59]:
from sklearn.ensemble import RandomForestClassifier

In [60]:
rf=RandomForestClassifier(n_estimators=100,random_state=42)

In [61]:
rf.fit(xtrain,ytrain)

RandomForestClassifier(random_state=42)

In [62]:
ypred=rf.predict(xtest)
# print(ypred)

<h1 style="color:red;">Accuracy</h1>

In [63]:
from sklearn.metrics import accuracy_score

In [64]:
acc=accuracy_score(ytest,ypred)
print('Acuuracy=',acc)

Acuuracy= 0.7988826815642458

In [65]:
from sklearn.metrics import classification_report

In [66]:
clsrep=classification_report(ytest,ypred)
print("Classicification Report",clsrep)

Classicification Report               precision    recall  f1-score   support

           0       0.82      0.85      0.83       105
           1       0.77      0.73      0.75        74

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

In [70]:
# rf.score(xtrain,ytrain)

0.9789325842696629

In [78]:
sample=xtest.iloc[0:1]

In [79]:
sample

     Pclass  Sex   Age  SibSp  Parch     Fare
709       3    1  28.0      1      1  15.2458

In [77]:
print(rf.predict(sample))

[0]

In [81]:
samp=xtest.iloc[0:10]
pred=rf.predict(samp)

In [82]:
samp

     Pclass  Sex   Age  SibSp  Parch     Fare
709       3    1  28.0      1      1  15.2458
439       2    1  31.0      0      0  10.5000
840       3    1  20.0      0      0   7.9250
720       2    0   6.0      0      1  33.0000
39        3    0  14.0      1      0  11.2417
290       1    0  26.0      0      0  78.8500
300       3    0  28.0      0      0   7.7500
333       3    1  16.0      2      0  18.0000
208       3    0  16.0      0      0   7.7500
136       1    0  19.0      0      2  26.2833

In [83]:
pred

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1], dtype=int64)